apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: webhooktest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        inject-node-selector: enabled
    spec:
      serviceAccountName: nginx-serviceaccount
      containers:
      - name: nginx
        image: nginx:latest
