# mutating-webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: node-selector-injector
  namespace: webhooktest
webhooks:
  - name: node-selector-injector.webhooktest.svc
    clientConfig:
      service:
        name: node-selector-injector
        namespace: default
        path: "/"
      caBundle: "TODO"
    rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
    failurePolicy: Fail
    matchPolicy: Equivalent
    namespaceSelector:
      matchLabels:
        node-selector-injector: enabled
    objectSelector:
      matchLabels:
        inject-node-selector: enabled
