apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
  namespace: webhooktest
  labels:
    app: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - name: webhook
        image: jonwoodlief/webhook:latest
        ports:
        - containerPort: 443
        volumeMounts:
          - name: tls
            mountPath: "/etc/admission-webhook/tls"
        env:
          - name: TLS
            value: "true"
      volumes:
        - name: tls
          secret:
            secretName: webhook-tls
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: webhooktest
spec:
  selector:
    app: webhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
