# mutating-webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: node-selector-injector
  namespace: webhooktest
webhooks:
  - name: webhook-service.webhooktest.svc
    clientConfig:
      service:
        name: webhook-service
        namespace: webhooktest
        path: "/mutate"
      caBundle: "TODO"
    rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
    failurePolicy: Fail
    matchPolicy: Equivalent
    namespaceSelector:
      matchLabels:
        node-selector-injector: enabled
    objectSelector:
      matchLabels:
        inject-node-selector: enabled
    sideEffects: None
    admissionReviewVersions: ["v1"]
